directories:
  output: release/
  buildResources: build
appId: com.example.companyDashboard
productName: angular-electron
files:
  - filter:
      - '**/*'
      - '!**/*.ts'
      - '!*.code-workspace'
      - '!LICENSE.md'
      - '!package.json'
      - '!package-lock.json'
      - '!src/'
      - '!e2e/'
      - '!hooks/'
      - '!angular.json'
      - '!_config.yml'
      - '!karma.conf.js'
      - '!tsconfig.json'
      - '!tslint.json'
win:
  icon: dist
  target:
    - portable
mac:
  icon: dist
  target:
    - dmg
linux:
  icon: dist
  target:
    - AppImage
electronVersion: 4.0.0
